apiVersion: invarity.dev/v1
kind: Tool
metadata:
  name: stripe.refund_payment
  version: 1.0.0
  description: Process a refund for a Stripe payment
  labels:
    provider: stripe
    domain: payments
    team: billing
  annotations:
    docs: https://stripe.com/docs/refunds
    owner: payments-team@example.com

spec:
  category: financial
  subcategory: refunds
  provider: Stripe

  parameters:
    type: object
    properties:
      payment_id:
        type: string
        description: The Stripe payment intent ID to refund
        pattern: "^pi_[a-zA-Z0-9]+$"
        riskWeight: medium
      amount:
        type: integer
        description: Amount to refund in cents (if omitted, full refund)
        minimum: 1
        maximum: 10000000
        riskWeight: high
      currency:
        type: string
        description: Three-letter ISO currency code
        pattern: "^[A-Z]{3}$"
        enum:
          - USD
          - EUR
          - GBP
          - CAD
          - AUD
      reason:
        type: string
        description: Reason for the refund
        enum:
          - duplicate
          - fraudulent
          - customer_request
          - other
      metadata:
        type: object
        description: Additional metadata for the refund
        properties:
          ticket_id:
            type: string
            description: Support ticket ID
          agent_id:
            type: string
            description: ID of the agent processing the refund
          escalation_level:
            type: integer
            minimum: 0
            maximum: 5
    required:
      - payment_id

  risk:
    baseLevel: high
    reversible: false
    requiresConfirmation: true
    factors:
      - name: high_amount
        impact: increases
        condition: "amount > 50000"
        magnitude: major
      - name: escalated_request
        impact: increases
        condition: "metadata.escalation_level >= 2"
        magnitude: moderate
      - name: known_customer
        impact: decreases
        condition: "context.user_verified == true"
        magnitude: minor
      - name: fraud_reason
        impact: increases
        condition: "reason == 'fraudulent'"
        magnitude: major

  capabilities:
    - write
    - transfer

  constraints:
    rateLimit:
      maxCalls: 100
      windowSeconds: 3600
    maxAmount: 1000000
    allowedCurrencies:
      - USD
      - EUR
      - GBP
      - CAD
      - AUD
    requiresApproval:
      threshold: 100000
      approvers:
        - finance-team
        - fraud-team

  examples:
    - description: Small refund for customer request
      input:
        payment_id: pi_example123
        amount: 2500
        currency: USD
        reason: customer_request
      expectedRisk: medium

    - description: Large refund requiring approval
      input:
        payment_id: pi_example456
        amount: 150000
        currency: USD
        reason: customer_request
        metadata:
          escalation_level: 3
      expectedRisk: critical

    - description: Fraud-related refund
      input:
        payment_id: pi_example789
        amount: 5000
        currency: EUR
        reason: fraudulent
      expectedRisk: high
