name: Infrastructure Deploy (Dev)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - diff
          - deploy

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  INVARITY_ENV: dev

jobs:
  deploy:
    name: CDK ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: invarity-infra-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK Diff
        run: npx cdk diff --all
        env:
          INVARITY_ENV: ${{ env.INVARITY_ENV }}

      - name: CDK Deploy
        if: github.event.inputs.action == 'deploy'
        run: npx cdk deploy --all --require-approval never --outputs-file cdk-outputs.json
        env:
          INVARITY_ENV: ${{ env.INVARITY_ENV }}

      - name: Upload CDK Outputs
        if: github.event.inputs.action == 'deploy'
        uses: actions/upload-artifact@v4
        with:
          name: cdk-outputs
          path: cdk-outputs.json
          retention-days: 7

      - name: Print Outputs
        if: github.event.inputs.action == 'deploy'
        run: |
          echo "=== Stack Outputs ==="
          cat cdk-outputs.json | jq '.'
